In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [3]:
feature = pd.read_csv("./Tetuan City power consumption.csv", index_col = 0)
features = feature
features = features.reset_index()

In [4]:
features


DateTime  Temperature  Humidity  Wind Speed  \
0         1/1/2017 0:00        6.559      73.8       0.083   
1         1/1/2017 0:10        6.414      74.5       0.083   
2         1/1/2017 0:20        6.313      74.5       0.080   
3         1/1/2017 0:30        6.121      75.0       0.083   
4         1/1/2017 0:40        5.921      75.7       0.081   
...                 ...          ...       ...         ...   
52411  12/30/2017 23:10        7.010      72.4       0.080   
52412  12/30/2017 23:20        6.947      72.6       0.082   
52413  12/30/2017 23:30        6.900      72.8       0.086   
52414  12/30/2017 23:40        6.758      73.0       0.080   
52415  12/30/2017 23:50        6.580      74.1       0.081   

       general diffuse flows  diffuse flows  Zone 1 Power Consumption  \
0                      0.051          0.119               34055.69620   
1                      0.070          0.085               29814.68354   
2                      0.062          0.100               29128.10127   
3                      0.091          0.096               28228.86076   
4                      0.048          0.085               27335.69620   
...                      ...            ...                       ...   
52411                  0.040          0.096               31160.45627   
52412                  0.051          0.093               30430.41825   
52413                  0.084          0.074               29590.87452   
52414                  0.066          0.089               28958.17490   
52415                  0.062          0.111               28349.80989   

       Zone 2  Power Consumption  Zone 3  Power Consumption  
0                    16128.87538                20240.96386  
1                    19375.07599                20131.08434  
2                    19006.68693                19668.43373  
3                    18361.09422                18899.27711  
4                    17872.34043                18442.40964  
...                          ...                        ...  
52411                26857.31820                14780.31212  
52412                26124.57809                14428.81152  
52413                25277.69254                13806.48259  
52414                24692.23688                13512.60504  
52415                24055.23167                13345.49820  

[52416 rows x 9 columns]

In [5]:
features['Zone 1 Power Consumption']

0        34055.69620
1        29814.68354
2        29128.10127
3        28228.86076
4        27335.69620
            ...     
52411    31160.45627
52412    30430.41825
52413    29590.87452
52414    28958.17490
52415    28349.80989
Name: Zone 1 Power Consumption, Length: 52416, dtype: float64

In [6]:
features.columns

Index(['DateTime', 'Temperature', 'Humidity', 'Wind Speed',
       'general diffuse flows', 'diffuse flows', 'Zone 1 Power Consumption',
       'Zone 2  Power Consumption', 'Zone 3  Power Consumption'],
      dtype='object')

In [7]:
features

DateTime  Temperature  Humidity  Wind Speed  \
0         1/1/2017 0:00        6.559      73.8       0.083   
1         1/1/2017 0:10        6.414      74.5       0.083   
2         1/1/2017 0:20        6.313      74.5       0.080   
3         1/1/2017 0:30        6.121      75.0       0.083   
4         1/1/2017 0:40        5.921      75.7       0.081   
...                 ...          ...       ...         ...   
52411  12/30/2017 23:10        7.010      72.4       0.080   
52412  12/30/2017 23:20        6.947      72.6       0.082   
52413  12/30/2017 23:30        6.900      72.8       0.086   
52414  12/30/2017 23:40        6.758      73.0       0.080   
52415  12/30/2017 23:50        6.580      74.1       0.081   

       general diffuse flows  diffuse flows  Zone 1 Power Consumption  \
0                      0.051          0.119               34055.69620   
1                      0.070          0.085               29814.68354   
2                      0.062          0.100               29128.10127   
3                      0.091          0.096               28228.86076   
4                      0.048          0.085               27335.69620   
...                      ...            ...                       ...   
52411                  0.040          0.096               31160.45627   
52412                  0.051          0.093               30430.41825   
52413                  0.084          0.074               29590.87452   
52414                  0.066          0.089               28958.17490   
52415                  0.062          0.111               28349.80989   

       Zone 2  Power Consumption  Zone 3  Power Consumption  
0                    16128.87538                20240.96386  
1                    19375.07599                20131.08434  
2                    19006.68693                19668.43373  
3                    18361.09422                18899.27711  
4                    17872.34043                18442.40964  
...                          ...                        ...  
52411                26857.31820                14780.31212  
52412                26124.57809                14428.81152  
52413                25277.69254                13806.48259  
52414                24692.23688                13512.60504  
52415                24055.23167                13345.49820  

[52416 rows x 9 columns]

In [8]:
#features=features.dropna(axis=0)



In [9]:
features


DateTime  Temperature  Humidity  Wind Speed  \
0         1/1/2017 0:00        6.559      73.8       0.083   
1         1/1/2017 0:10        6.414      74.5       0.083   
2         1/1/2017 0:20        6.313      74.5       0.080   
3         1/1/2017 0:30        6.121      75.0       0.083   
4         1/1/2017 0:40        5.921      75.7       0.081   
...                 ...          ...       ...         ...   
52411  12/30/2017 23:10        7.010      72.4       0.080   
52412  12/30/2017 23:20        6.947      72.6       0.082   
52413  12/30/2017 23:30        6.900      72.8       0.086   
52414  12/30/2017 23:40        6.758      73.0       0.080   
52415  12/30/2017 23:50        6.580      74.1       0.081   

       general diffuse flows  diffuse flows  Zone 1 Power Consumption  \
0                      0.051          0.119               34055.69620   
1                      0.070          0.085               29814.68354   
2                      0.062          0.100               29128.10127   
3                      0.091          0.096               28228.86076   
4                      0.048          0.085               27335.69620   
...                      ...            ...                       ...   
52411                  0.040          0.096               31160.45627   
52412                  0.051          0.093               30430.41825   
52413                  0.084          0.074               29590.87452   
52414                  0.066          0.089               28958.17490   
52415                  0.062          0.111               28349.80989   

       Zone 2  Power Consumption  Zone 3  Power Consumption  
0                    16128.87538                20240.96386  
1                    19375.07599                20131.08434  
2                    19006.68693                19668.43373  
3                    18361.09422                18899.27711  
4                    17872.34043                18442.40964  
...                          ...                        ...  
52411                26857.31820                14780.31212  
52412                26124.57809                14428.81152  
52413                25277.69254                13806.48259  
52414                24692.23688                13512.60504  
52415                24055.23167                13345.49820  

[52416 rows x 9 columns]

In [10]:
features.isna().sum()

DateTime                     0
Temperature                  0
Humidity                     0
Wind Speed                   0
general diffuse flows        0
diffuse flows                0
Zone 1 Power Consumption     0
Zone 2  Power Consumption    0
Zone 3  Power Consumption    0
dtype: int64

In [11]:
#print(features)

data = features.drop(columns=['DateTime', 'Zone 2  Power Consumption','Zone 3  Power Consumption'])

data

Temperature  Humidity  Wind Speed  general diffuse flows  \
0            6.559      73.8       0.083                  0.051   
1            6.414      74.5       0.083                  0.070   
2            6.313      74.5       0.080                  0.062   
3            6.121      75.0       0.083                  0.091   
4            5.921      75.7       0.081                  0.048   
...            ...       ...         ...                    ...   
52411        7.010      72.4       0.080                  0.040   
52412        6.947      72.6       0.082                  0.051   
52413        6.900      72.8       0.086                  0.084   
52414        6.758      73.0       0.080                  0.066   
52415        6.580      74.1       0.081                  0.062   

       diffuse flows  Zone 1 Power Consumption  
0              0.119               34055.69620  
1              0.085               29814.68354  
2              0.100               29128.10127  
3              0.096               28228.86076  
4              0.085               27335.69620  
...              ...                       ...  
52411          0.096               31160.45627  
52412          0.093               30430.41825  
52413          0.074               29590.87452  
52414          0.089               28958.17490  
52415          0.111               28349.80989  

[52416 rows x 6 columns]

In [12]:
data=data.dropna(axis=0)

#data=data.drop('PassengerId',axis=1)
#data = data.reset_index()

y=data['Zone 1 Power Consumption'].values

#y=y[:,1]
#print(type(y))
y

array([34055.6962 , 29814.68354, 29128.10127, ..., 29590.87452,
       28958.1749 , 28349.80989])

In [13]:
X=data.drop('Zone 1 Power Consumption',axis=1)
X


Temperature  Humidity  Wind Speed  general diffuse flows  diffuse flows
0            6.559      73.8       0.083                  0.051          0.119
1            6.414      74.5       0.083                  0.070          0.085
2            6.313      74.5       0.080                  0.062          0.100
3            6.121      75.0       0.083                  0.091          0.096
4            5.921      75.7       0.081                  0.048          0.085
...            ...       ...         ...                    ...            ...
52411        7.010      72.4       0.080                  0.040          0.096
52412        6.947      72.6       0.082                  0.051          0.093
52413        6.900      72.8       0.086                  0.084          0.074
52414        6.758      73.0       0.080                  0.066          0.089
52415        6.580      74.1       0.081                  0.062          0.111

[52416 rows x 5 columns]

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [15]:
X_train


Temperature  Humidity  Wind Speed  general diffuse flows  diffuse flows
39648        18.73     64.05       4.924                 65.920         48.050
11366        13.17     76.60       0.085                  0.077          0.104
32334        28.24     39.82       4.902                888.000         72.100
19331        17.56     83.60       0.068                  0.121          0.193
5834         11.78     87.60       4.920                100.400        101.000
...            ...       ...         ...                    ...            ...
21243        23.69     63.56       0.075                841.000        359.500
45891        23.25     48.57       0.086                180.100        193.400
42613        20.20     78.90       4.916                  0.059          0.137
43567        21.16     74.60       4.920                225.400        196.600
2732         10.58     54.86       0.092                  0.055          0.082

[39312 rows x 5 columns]

In [16]:
X_test

Temperature  Humidity  Wind Speed  general diffuse flows  diffuse flows
25500        20.46     89.70       4.916                  0.055          0.141
40040        20.59     68.96       4.920                  0.077          0.115
35066        27.01     46.78       4.922                784.000         66.450
27275        25.00     61.83       4.909                598.400         99.700
3329          9.85     70.80       0.083                  0.051          0.115
...            ...       ...         ...                    ...            ...
33495        29.03     48.12       4.923                808.000         80.600
48667        10.45     84.00       0.082                  0.044          0.115
4430         15.14     60.68       4.919                 11.910         12.340
16679        18.01     62.36       0.083                 13.520         11.880
33474        24.87     68.19       4.923                478.500        263.100

[13104 rows x 5 columns]

In [17]:
y_train

array([29222.23195, 39020.93617, 38331.8091 , ..., 37257.24289,
       33570.59081, 33502.78481])

In [18]:
y_test

array([27782.78146, 26386.34573, 27506.54867, ..., 43291.13924,
       45137.56728, 38319.02331])

In [26]:
# Regression
from sklearn import svm
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [23]:
# LR

model = LinearRegression()
model.fit(X_train, y_train)

ly_preds = model.predict(X_test)
mse = np.sqrt(mean_squared_error(ly_preds, y_test))
print('평균제곱근오차', mse)



평균제곱근오차 6368.602283603147


In [24]:
# RF

model = RandomForestRegressor()
model.fit(X_train, y_train)

ry_preds = model.predict(X_test)
mse = np.sqrt(mean_squared_error(ry_preds, y_test))
print('평균제곱근오차', mse)


평균제곱근오차 4751.346560877983


In [25]:
# DT

model = DecisionTreeRegressor()
model.fit(X_train, y_train)

dy_preds = model.predict(X_test)
mse = np.sqrt(mean_squared_error(dy_preds, y_test))
print('평균제곱근오차', mse)


평균제곱근오차 6680.724682405709


In [28]:
# SVM

model = SVR()
model.fit(X_train, y_train)

dy_preds = model.predict(X_test)
mse = np.sqrt(mean_squared_error(dy_preds, y_test))
print('평균제곱근오차', mse)


평균제곱근오차 7073.254295609563
